export type RetailerCode = 'cu' | 'gs25' | 'emart24'
export type PromotionType = 'none' | '1+1' | '2+1' | '3+1' | 'sale' | 'new'
export type Purpose = 'value' | 'meal' | 'diet' | 'protein' | 'night' | 'snack'
export type ProductCategory = 'meal' | 'drink' | 'protein' | 'snack' | 'fresh' | 'dessert'

export type Retailer = {
  code: RetailerCode
  name: string
  color: string
}

export type Product = {
  id: string
  retailer: RetailerCode
  brand: string
  name: string
  price: number
  category: ProductCategory
  promotionType: PromotionType
  purchaseQuantity: number
  rewardQuantity: number
  discountPrice?: number
  tags: Purpose[]
  startDate: string
  endDate: string
  collectedAt: string
  isNew?: boolean
}

export const retailers: Retailer[] = [
  { code: 'cu', name: 'CU', color: '#652f8f' },
  { code: 'gs25', name: 'GS25', color: '#1d6fd6' },
  { code: 'emart24', name: '이마트24', color: '#f0b323' },
]

export const purposes: Array<{ id: Purpose; label: string }> = [
  { id: 'value', label: '가성비' },
  { id: 'meal', label: '든든한 한 끼' },
  { id: 'diet', label: '가볍게' },
  { id: 'protein', label: '단백질' },
  { id: 'night', label: '야식' },
  { id: 'snack', label: '간식' },
]

export const products: Product[] = [
  {
    id: 'cu-rice-01',
    retailer: 'cu',
    brand: 'CU',
    name: '참치마요 삼각김밥',
    price: 1300,
    category: 'meal',
    promotionType: 'none',
    purchaseQuantity: 1,
    rewardQuantity: 1,
    tags: ['value', 'meal'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'cu-noodle-01',
    retailer: 'cu',
    brand: '농심',
    name: '육개장 컵라면',
    price: 1800,
    category: 'meal',
    promotionType: '2+1',
    purchaseQuantity: 2,
    rewardQuantity: 3,
    tags: ['value', 'meal', 'night'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'cu-drink-01',
    retailer: 'cu',
    brand: '코카콜라',
    name: '스프라이트 500ml',
    price: 2400,
    category: 'drink',
    promotionType: '1+1',
    purchaseQuantity: 1,
    rewardQuantity: 2,
    tags: ['value', 'snack', 'night'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'cu-protein-01',
    retailer: 'cu',
    brand: 'CU',
    name: '프로틴 초코우유',
    price: 2900,
    category: 'protein',
    promotionType: 'sale',
    purchaseQuantity: 1,
    rewardQuantity: 1,
    discountPrice: 2400,
    tags: ['protein', 'diet'],
    startDate: '2026-08-03',
    endDate: '2026-08-18',
    collectedAt: '2026-08-04 12:00',
    isNew: true,
  },
  {
    id: 'cu-snack-01',
    retailer: 'cu',
    brand: '오리온',
    name: '꼬북칩 매콤한맛',
    price: 1700,
    category: 'snack',
    promotionType: '1+1',
    purchaseQuantity: 1,
    rewardQuantity: 2,
    tags: ['value', 'snack', 'night'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'gs-rice-01',
    retailer: 'gs25',
    brand: 'GS25',
    name: '전주비빔 삼각김밥',
    price: 1400,
    category: 'meal',
    promotionType: 'none',
    purchaseQuantity: 1,
    rewardQuantity: 1,
    tags: ['value', 'meal'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'gs-protein-01',
    retailer: 'gs25',
    brand: '하림',
    name: '닭가슴살 오리지널',
    price: 3800,
    category: 'protein',
    promotionType: '1+1',
    purchaseQuantity: 1,
    rewardQuantity: 2,
    tags: ['protein', 'diet', 'meal'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'gs-noodle-01',
    retailer: 'gs25',
    brand: '팔도',
    name: '비빔면 컵',
    price: 1800,
    category: 'meal',
    promotionType: '2+1',
    purchaseQuantity: 2,
    rewardQuantity: 3,
    tags: ['value', 'meal', 'night'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'gs-fresh-01',
    retailer: 'gs25',
    brand: 'GS25',
    name: '반숙란 2입',
    price: 2300,
    category: 'protein',
    promotionType: 'none',
    purchaseQuantity: 1,
    rewardQuantity: 1,
    tags: ['protein', 'diet'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'gs-drink-01',
    retailer: 'gs25',
    brand: '코카콜라',
    name: '제로 콜라 500ml',
    price: 2200,
    category: 'drink',
    promotionType: '1+1',
    purchaseQuantity: 1,
    rewardQuantity: 2,
    tags: ['value', 'diet', 'snack', 'night'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'emart-choco-01',
    retailer: 'emart24',
    brand: '제로팜',
    name: '치즈초코 그래놀라볼 96g',
    price: 4500,
    category: 'dessert',
    promotionType: '1+1',
    purchaseQuantity: 1,
    rewardQuantity: 2,
    tags: ['snack', 'value'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
    isNew: true,
  },
  {
    id: 'emart-protein-01',
    retailer: 'emart24',
    brand: 'CJ',
    name: '밸런스밀 프로틴바 말차초코',
    price: 2900,
    category: 'protein',
    promotionType: '1+1',
    purchaseQuantity: 1,
    rewardQuantity: 2,
    tags: ['protein', 'diet', 'value'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'emart-rice-01',
    retailer: 'emart24',
    brand: '이마트24',
    name: '더블치즈 김밥',
    price: 3400,
    category: 'meal',
    promotionType: 'none',
    purchaseQuantity: 1,
    rewardQuantity: 1,
    tags: ['meal'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'emart-zero-01',
    retailer: 'emart24',
    brand: '이마트24',
    name: '제로 사이다 500ml',
    price: 2200,
    category: 'drink',
    promotionType: '1+1',
    purchaseQuantity: 1,
    rewardQuantity: 2,
    tags: ['diet', 'value', 'night'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
  {
    id: 'emart-egg-01',
    retailer: 'emart24',
    brand: '이마트24',
    name: '반숙란 2입',
    price: 2400,
    category: 'protein',
    promotionType: 'none',
    purchaseQuantity: 1,
    rewardQuantity: 1,
    tags: ['protein', 'diet'],
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    collectedAt: '2026-08-04 12:00',
  },
]
